modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="superkrassesprojekt"
version="1.0.0"
displayName="SuperKrassesProjekt"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="timki, MCreator"

[[dependencies.superkrassesprojekt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




